---
server:
  port: 8769
  use-forward-headers: false
  servlet:
    session:
      cookie:
        # Use different cookie name to avoid collisions.
        name: AUTH-SERVICE-SESSION

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}
