---
spring:
  application:
    name: auth-service

server:
  port: 8769
  use-forward-headers: false
  servlet:
    # Use different context-path to avoid session cookie overlapping.
    context-path: /auth

eureka:

  instance:
    hostname: localhost
    non-secure-port: ${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}

logging:
  level.org.springframework.security: DEBUG