server:
  port: 8764
  use-forward-headers: false
  servlet:
    session:
      cookie:
        # Use different cookie name to avoid collisions.
        name: AUTH-SERVICE-SESSION

---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}
