server:
  port: 8764
  use-forward-headers: false
  servlet:
    session:
      cookie:
        # Use different cookie name to avoid collisions.
        name: AUTH-SERVICE-SESSION

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#security:
#  oauth2:
#    client:
#
#      client-id: acme
#      client-secret: acmesecret
#      access-token-uri: http://localhost:${server.port}/oauth/token
#      user-authorization-uri: http://localhost:${server.port}/oauth/authorize
#    resource:
#      user-info-uri: http://localhost/userinfo
#      jwt:
#        key-value: "123"

#security:
#  oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}
