version: "3.1"

services:

  app-import:
    image: alpine:3.7
    depends_on:
    - dataflow-server
    command: >
      /bin/sh -c "
        while ! nc -z dataflow-server 9393;
        do
          sleep 1;
        done;
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=http://bit.ly/Celsius-SR3-stream-applications-kafka-10-maven&force=true';
        echo 'Stream apps imported'
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=http://bit.ly/Clark-GA-task-applications-maven&force=true';
        echo 'Task apps imported'"

#        wget -qO- 'http://dataflow-server:9393/apps/source/my-app' --post-data='uri=file:/root/apps/my-app.jar&metadata-uri=file:/root/apps/my-app-metadata.jar';
#        echo 'My custom apps imported'"

  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server-local:${DATAFLOW_VERSION}
    container_name: dataflow-server
    ports:
    - 9393:9393
    - 9000-9010:9000-9010
    environment:
    - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=kafka:9092
    - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes=zookeeper:2181
    - spring_datasource_url=jdbc:postgresql://postgres:5432/dataflow
    - spring_datasource_username=dataflow
    - spring_datasource_password=dataflow
    - spring_datasource_driver-class-name=org.postgresql.Driver
    - spring.cloud.dataflow.applicationProperties.stream.spring.redis.host=redis
    - spring_redis_host=redis
    depends_on:
    - kafka
    - postgres
    - redis
#    volumes:
#    - ./apps:/root/apps

  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
    - 9092:9092
    environment:
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ADVERTISED_HOST_NAME=kafka
    depends_on:
    - zookeeper

  redis:
    image: redis
    ports:
    - ${REDIS_HOST_PORT}:6379

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dataflow
      POSTGRES_PASSWORD: dataflow
      POSTGRES_DB: dataflow
    ports:
    - ${POSTGRES_HOST_PORT}:5432

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
    - 2181