version: "3.1"

services:

  admin-ui:
    image: spring-ecosystem/admin-ui
    environment:
      SERVICE_PORT: ${ADMIN_UI_PORT:-8762}
      REGISTRY_URI: ${REGISTRY_URI}
    ports:
    - ${ADMIN_UI_HOST_PORT:-8762}:${ADMIN_UI_PORT:-8762}
    depends_on:
    - config-service
    - service-registry
    restart: on-failure

  api-gateway:
    image: spring-ecosystem/api-gateway
    environment:
      SERVICE_PORT: ${API_GATEWAY_PORT:-8763}
      REGISTRY_URI: ${REGISTRY_URI}
    ports:
    - ${API_GATEWAY_HOST_PORT:-8763}:${API_GATEWAY_PORT:-8763}
    depends_on:
    - config-service
    - service-registry
    restart: on-failure

  auth-service:
    image: spring-ecosystem/auth-service
    environment:
      SERVICE_PORT: ${AUTH_SERVICE_PORT:-8769}
      REGISTRY_URI: ${REGISTRY_URI}
    depends_on:
    - config-service
    - service-registry
    restart: on-failure
    ports:
    - ${AUTH_SERVICE_HOST_PORT:-8769}:${AUTH_SERVICE_PORT:-8769}

  config-service:
    image: spring-ecosystem/config-service
    environment:
      SERVICE_PORT: ${CONFIG_SERVICE_PORT:-8888}
      REGISTRY_URI: ${REGISTRY_URI}
    ports:
    - ${CONFIG_SERVICE_HOST_PORT:-8888}:${CONFIG_SERVICE_PORT:-8888}

  panel-service:
    image: spring-ecosystem/panel-service
    environment:
      SERVICE_PORT: ${PANEL_SERVICE_PORT:-0}
      REGISTRY_URI: ${REGISTRY_URI}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT:-8763}
    depends_on:
    - config-service
    - service-registry
    restart: on-failure
    ports:
    - ${PANEL_SERVICE_PORT_HOST_PORT:-8769}:${PANEL_SERVICE_PORT:-0}

  service-registry:
    image: spring-ecosystem/service-registry
    environment:
      SERVICE_HOST: service-registry
      SERVICE_PORT: ${REGISTRY_PORT:-8761}
      CONFIG_SERVICE_URI: ${CONFIG_SERVICE_URI}
    ports:
    - ${REGISTRY_HOST_PORT:-8761}:${REGISTRY_PORT:-8761}
    depends_on:
    - config-service

  zipkin:
    image: spring-ecosystem/zipkin
    environment:
      SERVICE_PORT: ${ZIPKIN_PORT:-9411}
      REGISTRY_URI: ${REGISTRY_URI}
    ports:
    - ${ZIPKIN_HOST_PORT:-9411}:${ZIPKIN_PORT:-9411}
