server:
  port: 8763

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}