---
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo

# TODO: How can this be fetched from the config repo like it is for everything else?
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka

server:
  port: 8888

---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}

# TODO: How can this be fetched from the config repo like it is for everything else?
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}