server:
  port: 0

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krixon/spring-ecosystem-config.git

---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}